app = "cflgateway"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL = "info"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

